services:

  dns:
    build: ./dns
    container_name: dns_service
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/config:/etc/bind
    restart: unless-stopped
    networks:
      reseau_services:
        ipv4_address: 172.20.0.10

  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft_bedrock_service
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: easy
      ALLOW_CHEATS: "false"
      LEVEL_NAME: "Bedrock_level"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./minecraft:/data
    restart: unless-stopped
    networks:
      - reseau_services

  music_s_service:
    build: ./Music_S
    container_name: music_s_service
    ports:
      - "5555:5555"
    restart: unless-stopped
    networks:
      - reseau_services
    dns:
      - 8.8.8.8
      - 1.1.1.1

  web:
    build: ./web
    container_name: web_service
    ports:
      - "80:80"
    volumes:
      - ./web/sites/html/Porte_Folio/Music_s/:/usr/local/apache2/htdocs/Music_s
      - ./web/sites/html/Porte_Folio/:/usr/local/apache2/htdocs/Porte_Folio
      - ./web/sites/virtualHosts/:/usr/local/apache2/conf/extra/
    restart: unless-stopped
    networks:
      - reseau_services

networks:
  reseau_services:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
