services:

  dns:
    build: ./dns
    container_name: dns_service
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./Linux-home/dns/config:/etc/bind
    restart: unless-stopped
    networks:
      reseau_services:
        ipv4_address: 172.20.0.10

  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft_bedrock_service
    environment:
      EULA: "TRUE"
      GAMEMODE: survival   # optionnel : survival, creative, adventure, spectator
      DIFFICULTY: easy     # easy, normal, hard, peaceful
      ALLOW_CHEATS: "false"
    ports:
      - "19132:19132/udp"  # port Bedrock par défaut en UDP
    volumes:
      - ./Linux-home/minecraft_bedrock:/data
    restart: unless-stopped
    networks:
      - reseau_services

  music_s:
    build: ./Music_S
    container_name: music_s_service
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - reseau_services

  web:
    image: httpd:2.4
    container_name: web_service
    ports:
      - "80:80"
    volumes:
      - ./Linux-home/web/Music_s/:/usr/local/apache2/htdocs/
      - ./Linux-home/web/sites/virtualHosts:/usr/local/apache2/conf/extra/
    restart: unless-stopped
    networks:
      - reseau_services

networks:
  reseau_services:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
